package com.mastek.topcoders.smartkanteen.bean;

// Generated Dec 4, 2014 12:33:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * DailyMenu generated by hbm2java
 */
public class DailyMenu implements java.io.Serializable
{

	private int dailyMenuId;
	private int catererId;
	private Date menuDate;
	private Set<DailyMenuMapping> dailyMenuMapping;
	private List<Menu> menuList;

	public int getDailyMenuId()
	{
		return dailyMenuId;
	}

	public void setDailyMenuId(int dailyMenuId)
	{
		this.dailyMenuId = dailyMenuId;
	}

	public int getCatererId()
	{
		return catererId;
	}

	public void setCatererId(int catererId)
	{
		this.catererId = catererId;
	}

	public Date getMenuDate()
	{
		return menuDate;
	}

	public void setMenuDate(Date menuDate)
	{
		this.menuDate = menuDate;
	}

	public Set<DailyMenuMapping> getDailyMenuMapping()
	{
		return dailyMenuMapping;
	}

	public void setDailyMenuMapping(Set<DailyMenuMapping> dailyMenuMapping)
	{
		this.dailyMenuMapping = dailyMenuMapping;
	}

	public List<Menu> getMenuList()
	{
		return menuList;
	}

	public void setMenuList(List<Menu> menuList)
	{
		this.menuList = menuList;
	}

	@Override
	public String toString()
	{
		return "DailyMenu [dailyMenuId=" + dailyMenuId + ", catererId=" + catererId + ", menuDate=" + menuDate
				+ ", dailyMenuMapping=" + dailyMenuMapping + ", menuList=" + menuList + "]";
	}
}