package com.mastek.topcoders.smartkanteen.bean;

// Generated Dec 4, 2014 12:33:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * MenuMaster generated by hbm2java
 */
@XmlRootElement
public class Menu implements java.io.Serializable
{

	private int itemId;
	private String itemName;
	private String description;
	private BigDecimal price;
	private int prepTime;

	public int getItemId()
	{
		return itemId;
	}

	public void setItemId(int itemId)
	{
		this.itemId = itemId;
	}

	public String getItemName()
	{
		return itemName;
	}

	public void setItemName(String itemName)
	{
		this.itemName = itemName;
	}

	public String getDescription()
	{
		return description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public BigDecimal getPrice()
	{
		return price;
	}

	public void setPrice(BigDecimal price)
	{
		this.price = price;
	}

	public int getPrepTime()
	{
		return prepTime;
	}

	public void setPrepTime(int prepTime)
	{
		this.prepTime = prepTime;
	}

	@Override
	public String toString()
	{
		return "MenuMaster [itemId=" + itemId + ", itemName=" + itemName + ", description=" + description + ", price="
				+ price + ", prepTime=" + prepTime + "]";
	}
}
