package com.mastek.topcoders.smartkanteen.bean;

// Generated Dec 17, 2014 3:22:14 PM by Hibernate Tools 3.4.0.CR1

/**
 * MenuTagsMapping generated by hbm2java
 */
public class MenuTagsMapping implements java.io.Serializable
{
	private Integer menuTagsMappingId;
	private Integer itemId;
	private String tags;

	public Integer getMenuTagsMappingId()
	{
		return menuTagsMappingId;
	}

	public void setMenuTagsMappingId(Integer menuTagsMappingId)
	{
		this.menuTagsMappingId = menuTagsMappingId;
	}

	public Integer getItemId()
	{
		return itemId;
	}

	public void setItemId(Integer itemId)
	{
		this.itemId = itemId;
	}

	public String getTags()
	{
		return tags;
	}

	public void setTags(String tags)
	{
		this.tags = tags;
	}

	@Override
	public String toString()
	{
		return "MenuTagsMapping [menuTagsMappingId=" + menuTagsMappingId + ", itemId=" + itemId + ", tags=" + tags
				+ "]";
	}
}
