package com.mastek.topcoders.smartkanteen.bean;

// Generated Dec 19, 2014 7:06:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails implements java.io.Serializable
{
	private Integer orderDetailsId;
	private OrderMaster orderMaster;
	private DailyMenuMapping dailyMenuMapping;

	public Integer getOrderDetailsId()
	{
		return orderDetailsId;
	}

	public void setOrderDetailsId(Integer orderDetailsId)
	{
		this.orderDetailsId = orderDetailsId;
	}

	public OrderMaster getOrderMaster()
	{
		return orderMaster;
	}

	public void setOrderMaster(OrderMaster orderMaster)
	{
		this.orderMaster = orderMaster;
	}

	public DailyMenuMapping getDailyMenuMapping()
	{
		return dailyMenuMapping;
	}

	public void setDailyMenuMapping(DailyMenuMapping dailyMenuMapping)
	{
		this.dailyMenuMapping = dailyMenuMapping;
	}

	@Override
	public String toString()
	{
		return "OrderDetails [orderDetailsId=" + orderDetailsId + ", orderMaster=" + orderMaster
				+ ", dailyMenuMapping=" + dailyMenuMapping + "]";
	}
}
