package com.mastek.topcoders.smartkanteen.bean;

import javax.xml.bind.annotation.XmlRootElement;

//Generated Dec 30, 2014 11:55:11 AM by Hibernate Tools 3.4.0.CR1

/**
* OrderDetails generated by hbm2java
*/
@XmlRootElement
public class OrderDetails
{

	private Integer orderDetailsId;
	private Menu menu;
	private Integer menuId;
//	private OrderMaster orderMaster;
	private Integer quantity;
	
	public OrderDetails() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Integer getOrderDetailsId()
	{
		return orderDetailsId;
	}

	public void setOrderDetailsId(Integer orderDetailsId)
	{
		this.orderDetailsId = orderDetailsId;
	}

	public Menu getMenu()
	{
		return menu;
	}

	public void setMenu(Menu menu)
	{
		this.menu = menu;
	}

//	public OrderMaster getOrderMaster()
//	{
//		return orderMaster;
//	}

//	public void setOrderMaster(OrderMaster orderMaster)
//	{
//		this.orderMaster = orderMaster;
//	}

	public Integer getQuantity()
	{
		return quantity;
	}

	public void setQuantity(Integer quantity)
	{
		this.quantity = quantity;
	}

	public Integer getMenuId() {
		return menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}
	
	@Override
	public String toString()
	{
		return "OrderDetails [orderDetailsId=" + orderDetailsId + ", menu=" + menu + ", quantity=" + quantity + "]";
	}
}
