package com.mastek.topcoders.smartkanteen.bean;

// Generated Dec 19, 2014 7:06:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

/**
 * OrderMaster generated by hbm2java
 */
public class OrderMaster implements java.io.Serializable
{
	private Integer orderId;
	private User user;
	private BigDecimal totalCost;
	private Date orderDate;
	private String status;
	private String remark;
	private Set<OrderDetails> orderDetails;

	public Integer getOrderId()
	{
		return orderId;
	}

	public void setOrderId(Integer orderId)
	{
		this.orderId = orderId;
	}

	public User getUser()
	{
		return user;
	}

	public void setUser(User user)
	{
		this.user = user;
	}

	public BigDecimal getTotalCost()
	{
		return totalCost;
	}

	public void setTotalCost(BigDecimal totalCost)
	{
		this.totalCost = totalCost;
	}

	public Date getOrderDate()
	{
		return orderDate;
	}

	public void setOrderDate(Date orderDate)
	{
		this.orderDate = orderDate;
	}

	public String getStatus()
	{
		return status;
	}

	public void setStatus(String status)
	{
		this.status = status;
	}

	public String getRemark()
	{
		return remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Set<OrderDetails> getOrderDetails()
	{
		return orderDetails;
	}

	public void setOrderDetails(Set<OrderDetails> orderDetails)
	{
		this.orderDetails = orderDetails;
	}

	@Override
	public String toString()
	{
		return "OrderMaster [orderId=" + orderId + ", user=" + user + ", totalCost=" + totalCost + ", orderDate="
				+ orderDate + ", status=" + status + ", remark=" + remark + ", orderDetails=" + orderDetails + "]";
	}
}
