package com.mastek.topcoders.smartkanteen.bean;

// Generated Dec 17, 2014 3:22:14 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tags generated by hbm2java
 */
public class Tag implements java.io.Serializable
{
	private Integer tagId;
	private String tagName;

	public Integer getTagId()
	{
		return tagId;
	}

	public void setTagId(Integer tagId)
	{
		this.tagId = tagId;
	}

	public String getTagName()
	{
		return tagName;
	}

	public void setTagName(String tagName)
	{
		this.tagName = tagName;
	}

	@Override
	public String toString()
	{
		return "Tag [tagId=" + tagId + ", tagName=" + tagName + "]";
	}
}
