package com.mastek.topcoders.smartkanteen.bean;

// Generated Dec 24, 2014 2:31:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserDetails generated by hbm2java
 */
public class UserDetails implements java.io.Serializable
{

	private Integer userDetailsId;
	private User user;
	private String firstName;
	private String lastName;
	private String gender;
	private Date dateOfBirth;
	private Long contactNo;
	private Integer extensionNo;
	private Integer employeeId;

	public User getUser()
	{
		return user;
	}

	public void setUser(User userId)
	{
		this.user = userId;
	}

	public Integer getUserDetailsId()
	{
		return this.userDetailsId;
	}

	public void setUserDetailsId(Integer userDetailsId)
	{
		this.userDetailsId = userDetailsId;
	}

	public String getFirstName()
	{
		return this.firstName;
	}

	public void setFirstName(String firstName)
	{
		this.firstName = firstName;
	}

	public String getLastName()
	{
		return this.lastName;
	}

	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	public String getGender()
	{
		return this.gender;
	}

	public void setGender(String gender)
	{
		this.gender = gender;
	}

	public Date getDateOfBirth()
	{
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth)
	{
		this.dateOfBirth = dateOfBirth;
	}

	public Long getContactNo()
	{
		return this.contactNo;
	}

	public void setContactNo(Long contactNo)
	{
		this.contactNo = contactNo;
	}

	public Integer getExtensionNo()
	{
		return this.extensionNo;
	}

	public void setExtensionNo(Integer extensionNo)
	{
		this.extensionNo = extensionNo;
	}

	public Integer getEmployeeId()
	{
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId)
	{
		this.employeeId = employeeId;
	}

	@Override
	public String toString()
	{
		return "UserDetails [userDetailsId=" + userDetailsId + ", firstName=" + firstName + ", lastName=" + lastName
				+ ", gender=" + gender + ", dateOfBirth=" + dateOfBirth + ", contactNo=" + contactNo + ", extensionNo="
				+ extensionNo + ", employeeId=" + employeeId + "]";
	}
}
