package com.mastek.topcoders.smartkanteen.bean;

// Generated Jan 8, 2015 11:37:21 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserCatererMapping generated by hbm2java
 */
public class UserCatererMapping implements java.io.Serializable
{

	private Integer userCatererMappingId;
	private Integer userId;
	private Caterer caterer;

	public Integer getUserCatererMappingId()
	{
		return userCatererMappingId;
	}

	public void setUserCatererMappingId(Integer userCatererMappingId)
	{
		this.userCatererMappingId = userCatererMappingId;
	}

	public Integer getUserId()
	{
		return userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public Caterer getCaterer()
	{
		return caterer;
	}

	public void setCaterer(Caterer caterer)
	{
		this.caterer = caterer;
	}

	@Override
	public String toString()
	{
		return "UserCatererMapping [userCatererMappingId=" + userCatererMappingId + ", userId=" + userId + ", caterer="
				+ caterer + "]";
	}
}
